<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form-signin');
$form->setAttribute('role', 'form');

$identity = $form->get('identity');
$identity->setAttributes(['placeholder' => $identity->getLabel()]);

$credential = $form->get('credential');
$credential->setAttributes(['placeholder' => $credential->getLabel()]);

$button = $form->get('submit');
$button->setAttributes(['class' => 'btn btn-primary']);
?>
<div class="row">
    <?php echo $this->form()->openTag($form) ?>
        <div class="form-signin-header">
            <img src="<?php echo $this->basePath('img/logo.png') ?>" alt="Mega Mitch Credit, Inc." class="img-responsive center-block" onclick="location.href='<?php echo $this->url("home"); ?>'">
            <p class="text-center"><strong>MMCI Office Tool (MOT) User Login</strong></p>
        </div>
        <div class="form-group">
            <?php echo $this->formElementErrors()->setAttributes(['class' => 'alert-warning'])->render($identity) ?>
        </div>
        <div class="form-group"> 
            <?php echo $this->formInput($identity) ?>
            <?php echo $this->formInput($credential) ?>
        </div>
        <div class="btn-toolbar">
            <?php echo $this->formButton($button) ?>
        </div>
    <?php echo $this->form()->closeTag() ?>
</div>