<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form-signin');
$form->setAttribute('role', 'form');

$identity = $form->get('identity');
$identity->setAttributes(['placeholder' => $identity->getLabel()]);

$credential = $form->get('credential');
$credential->setAttributes(['placeholder' => $credential->getLabel()]);

$button = $form->get('submit');
$button->setAttributes(['class' => 'btn btn-primary']);
?>


<?php echo $this->form()->openTag($form) ?>
<div class="form-signin-header">
    <a href="<?php echo $this->url('home'); ?>">
        <img src="<?php echo $this->basePath('img/logo.png') ?>" alt="Mega Mitch Credit, Inc.">            
    </a>
    <p><strong>MMCI Office Tool (MOT) internal application</strong></p>
</div>
<div class="form-group-sm">
    <?php echo $this->formElementErrors($identity) ?>
</div>            
<div class="form-group"> 
    <?php echo $this->formInput($identity) ?>
    <?php echo $this->formInput($credential) ?>
</div>            
<?php echo $this->formButton($button) ?>
<?php echo $this->form()->closeTag() ?>

<?php if ($this->enableRegistration) : ?>
<?php echo $this->translate('Not registered?'); ?> <a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>"><?php echo $this->translate('Sign up!'); ?></a>
<?php endif; ?>
